# Generated by Django 4.0.2 on 2022-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_newitems_remove_transactionitems_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
