# Generated by Django 4.0.2 on 2022-04-25 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_email_remove_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='menu_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.menuitems'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
