# Generated by Django 4.0.2 on 2022-05-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ingredients_menu_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
