# Generated by Django 4.0.2 on 2022-05-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_transaction_id_orderitems_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='Not Started', max_length=255),
            preserve_default=False,
        ),
    ]
