# Generated by Django 4.0.2 on 2022-03-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orderitems'),
    ]

    operations = [
    ]
