# Generated by Django 4.0.2 on 2022-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Not Started', max_length=255),
            preserve_default=False,
        ),
    ]
