# Generated by Django 3.2.13 on 2022-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='items',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(default='Not Started', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Not Started', max_length=255),
        ),
    ]
