# Generated by Django 3.2.13 on 2022-05-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220502_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.transactions'),
        ),
    ]
