# Generated by Django 3.2.13 on 2022-06-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reservations_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='reservations',
        ),
        migrations.AddField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tables'),
        ),
    ]
